server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: servicelogin
  datasource:
       platform: mysql
       url: jdbc:mysql://192.168.0.249:3306/testdb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
       username: vrkb
       password: 3dms
       driverClassName: com.mysql.jdbc.Driver


mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.SpringCloudEurekaClient.model