server:
  port: 8041
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.160:8761/eureka/
  instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
spring:
  datasource:
       platform: 
       url: 
       username: 
       password: 
       driverClassName: 
mybatis:
    mapper-locations: classpath:/mapper/*.xml
    configLocation: classpath:mybatis.xml
    type-aliases-package: com.SpringCloudConfigClient.Model