server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.160:8761/eureka/
  instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
spring:
  application:
    name: servicelogin
  datasource:
       platform: mysql
       url: jdbc:mysql://192.168.0.249:3306/testdb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
       username: vrkb
       password: 3dms
       driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.0.160
    port: 6379
    pool:
     max-idle: 8
     min-idle: 0
     max-active: 8
     max-wait: -1
     maxTotal: 8
     maxWaitMillis: 1000
mybatis:
    mapper-locations: classpath:/mapper/*.xml
    configLocation: classpath:mybatis.xml
    type-aliases-package: com.SpringCloudEurekaClient.model



    
