server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-client
zuul:
  ignoredServices: '*'
  routes:
    microservice-provider-user: /ecom/**
